import unittest

import numpy as np

from src.observation_operator import RadarObservationOperator


class ObservationOperatorAnalyticTest(unittest.TestCase):
    """Analytic expectations below are specified independently of H."""

    @staticmethod
    def _project(wind, azimuth_deg, elevation_deg=0.0):
        operator = RadarObservationOperator.from_azimuth_elevation(
            np.array([azimuth_deg]), np.array([elevation_deg])
        )
        return float(operator.forward(np.asarray(wind)[:, np.newaxis])[0])

    def test_pure_east_wind_on_eastward_beam_is_positive(self):
        self.assertAlmostEqual(self._project((12.0, 0.0, 0.0), 90.0), 12.0)

    def test_east_wind_seen_on_westward_beam_is_negative(self):
        self.assertAlmostEqual(self._project((12.0, 0.0, 0.0), 270.0), -12.0)

    def test_pure_west_wind_on_eastward_beam_is_negative(self):
        self.assertAlmostEqual(self._project((-8.0, 0.0, 0.0), 90.0), -8.0)

    def test_pure_north_wind_on_northward_beam_is_positive(self):
        self.assertAlmostEqual(self._project((0.0, 7.0, 0.0), 0.0), 7.0)

    def test_pure_upward_wind_on_vertical_beam_is_positive(self):
        self.assertAlmostEqual(self._project((0.0, 0.0, 3.0), 137.0, 90.0), 3.0)

    def test_general_three_dimensional_wind(self):
        # Hand-calculated for (u,v,w)=(3,-4,2), azimuth=35 deg,
        # elevation=20 deg; the expected value is not generated by H.
        expected = -0.778007604541623
        self.assertAlmostEqual(
            self._project((3.0, -4.0, 2.0), 35.0, 20.0), expected, places=13
        )


class ObservationOperatorAdjointTest(unittest.TestCase):
    def test_random_mask_and_weights(self):
        worst_relative_error = 0.0
        for seed in range(10):
            rng = np.random.default_rng(seed)
            shape = (5, 7, 9)
            azimuth = rng.uniform(0.0, 360.0, shape)
            elevation = rng.uniform(-3.0, 35.0, shape)
            mask = rng.random(shape) > 0.31
            weights = rng.lognormal(mean=0.0, sigma=1.0, size=shape)
            weights[rng.random(shape) < 0.13] = 0.0

            operator = RadarObservationOperator.from_azimuth_elevation(
                azimuth, elevation, valid_mask=mask
            )
            wind = rng.normal(size=(3,) + shape)
            radial_test = rng.normal(size=shape)

            left = np.vdot(
                operator.weighted_forward(wind, weights), radial_test
            )
            right = np.vdot(
                wind, operator.weighted_adjoint(radial_test, weights)
            )
            denominator = max(abs(left), abs(right), np.finfo(float).eps)
            relative_error = float(abs(left - right) / denominator)
            worst_relative_error = max(worst_relative_error, relative_error)

        self.assertLessEqual(worst_relative_error, 1.0e-7)

    def test_masked_rows_and_adjoint_columns_are_zero(self):
        mask = np.array([True, False, True])
        operator = RadarObservationOperator.from_azimuth_elevation(
            np.array([0.0, 90.0, 180.0]),
            np.zeros(3),
            valid_mask=mask,
        )
        wind = np.ones((3, 3))
        self.assertEqual(operator.forward(wind)[1], 0.0)
        self.assertTrue(np.all(operator.adjoint(np.ones(3))[:, 1] == 0.0))


if __name__ == "__main__":
    unittest.main()
